import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import Background from '@/components/Background/Background'

const inter = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="text-xl text-slate-800 leading-7 tracking-wide flex flex-col items-center w-full relative">
          <Background />
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
